### ISSUE TITLE
'AnyWhich' not found

### ISSUE THREAD

**Issue by mjaniec2013** [HughParsonage/hutilscpp#2]
'AnyWhich' function is not working.

```
library(hutilscpp)

AnyWhich(x, 1)
> Error in AnyWhich(x, 1) : could not find function "AnyWhich"

AnyWhich
> Error: object 'AnyWhich' not found
```

**Comment by HughParsonage** [comment]
Hi, `AnyWhich` is just an internal documentation entry at the moment, not an exported function.

What are you trying to do?

**Comment by mjaniec2013** [comment]
I've been just testing the package and tried `AnyWhich`, since it is in the package documentation and is not described as internal.

Also, for some time I've been looking for a faster version of `which `function.

**Comment by HughParsonage** [comment]
OK thank you. I agree the documentation is unclear. I'll change it.
